from __future__ import annotations

from .models import ExperimentRun


def _cpp_int_vector(values: tuple[int, ...]) -> str:
    return "{" + ", ".join(str(value) for value in values) + "}"


def _cpp_float(value: float) -> str:
    return format(value, ".17g")


def _cpp_float_vector(values: tuple[float, ...]) -> str:
    return "{" + ", ".join(_cpp_float(value) for value in values) + "}"


def _parameter_block(run: ExperimentRun) -> str:
    matrix_rows = []
    for row in run.migration_matrix:
        matrix_rows.append("{" + ", ".join(_cpp_float(value) for value in row) + "}")
    matrix = "{" + ",\n        ".join(matrix_rows) + "}"
    return f"""
    std::vector<int> pop_sizes = {_cpp_int_vector(run.population_sizes)};
    std::vector<double> ss = {_cpp_float_vector(run.selection_coefficients)};
    std::vector<std::vector<double>> ms = {{
        {matrix[1:-1]}
    }};

    Parameter para;
    para.ss = ss;
    para.ms = ms;
    para.pop_sizes = pop_sizes;
""".strip()


def render_main(run: ExperimentRun, program: str) -> str:
    if program not in {"theory", "simulation"}:
        raise ValueError("program must be 'theory' or 'simulation'.")
    if run.model == "new_mutation" and program == "theory":
        return _new_mutation_theory(run)
    if run.model == "new_mutation" and program == "simulation":
        return _new_mutation_simulation(run)
    if run.model == "from_equilibrium" and program == "theory":
        return _equilibrium_theory(run)
    return _equilibrium_simulation(run)


def _includes(*headers: str) -> str:
    standard = ["iostream", "vector", "cmath", "string", "filesystem", "random"]
    lines = [f"#include <{header}>" for header in standard]
    lines.extend(f'#include "{header}"' for header in headers)
    return "\n".join(lines)


def _trajectory_block(run: ExperimentRun) -> str:
    return f"""
    int sep = {run.sep};
    {_parameter_block(run)}

    std::vector<double> ave_freq;
    std::vector<std::vector<double>> freq_each;
    Detsimu det(para);
    double conv = 1.0;
    double conv_crit = 1.0;
    while (conv > 1.5 / 4.0 / sep) {{
        conv = det.calculate_det_trajectory(4 * sep, ave_freq, freq_each, conv_crit);
        conv_crit /= 10.0;
    }}
""".strip()


def _new_mutation_theory(run: ExperimentRun) -> str:
    return f"""// Generated by multipopulation-experiment-runner. Do not edit manually.
{_includes('parameter.hpp', 'detsimu.hpp', 'diffusion.hpp')}

int main() {{
    int ini_pop = {run.initial_population};
    {_trajectory_block(run)}

    if (conv < -0.5) {{
        std::cout << "error: fail to construct deterministic trajectory" << std::endl;
    }} else {{
        double inv1 = det.ret_invasion1();
        if (inv1 < 1e-8) {{
            std::cout << "allele A is not invasive" << std::endl;
        }} else {{
            Diffusion diff(para, ini_pop, sep, ave_freq, freq_each);
            diff.calculate_diffusion();
            std::cout << "invasive or not : " << diff.return_invasion() << std::endl;
            std::cout << "applicable or not : " << diff.return_convergence() << std::endl;
            std::cout << "max lambda : " << diff.return_max_eigen() << std::endl;
            std::cout << "absorption time : " << diff.return_sum_sojourn() << std::endl;
        }}
    }}
    return 0;
}}
"""


def _new_mutation_simulation(run: ExperimentRun) -> str:
    return f"""// Generated by multipopulation-experiment-runner. Do not edit manually.
{_includes('parameter.hpp', 'stocsimu.hpp')}

int main() {{
    int ini_pop = {run.initial_population};
    int rep = {run.replicates};
    {_parameter_block(run)}
    Stocsimu stoc(para, ini_pop, rep);
    stoc.run_simulation();
    return 0;
}}
"""


def _equilibrium_theory(run: ExperimentRun) -> str:
    return f"""// Generated by multipopulation-experiment-runner. Do not edit manually.
{_includes('parameter.hpp', 'detsimu.hpp', 'diffusion.hpp')}

int main() {{
    {_trajectory_block(run)}

    if (conv < -0.5) {{
        std::cout << "error: fail to construct deterministic trajectory" << std::endl;
    }} else {{
        double inv1 = det.ret_invasion1();
        double inv2 = det.ret_invasion2();
        double equ_ave_freq = det.return_fin_ave_freq();
        if (inv1 < 1e-8 || inv2 < 1e-8) {{
            std::cout << "either of the alleles is not invasive" << std::endl;
        }} else {{
            Diffusion diff(para, equ_ave_freq, sep, ave_freq, freq_each);
            diff.calculate_diffusion();
            std::cout << "applicable or not : " << diff.return_convergence() << std::endl;
            std::cout << "max lambda : " << diff.return_max_eigen() << std::endl;
            std::cout << "absorption time : " << diff.return_sum_sojourn() << std::endl;
        }}
    }}
    return 0;
}}
"""


def _equilibrium_simulation(run: ExperimentRun) -> str:
    return f"""// Generated by multipopulation-experiment-runner. Do not edit manually.
{_includes('parameter.hpp', 'detsimu.hpp', 'stocsimu.hpp')}

int main() {{
    int rep = {run.replicates};
    {_trajectory_block(run)}

    if (conv < -0.5) {{
        std::cout << "error: fail to construct deterministic trajectory" << std::endl;
    }} else {{
        double inv1 = det.ret_invasion1();
        double inv2 = det.ret_invasion2();
        std::vector<double> equ_freq = det.return_fin_freq();
        if (inv1 < 1e-8 || inv2 < 1e-8) {{
            std::cout << "either of the alleles is not invasive" << std::endl;
        }} else {{
            Stocsimu stoc(para, equ_freq, rep);
            stoc.run_simulation();
        }}
    }}
    return 0;
}}
"""
